
FROM node

EXPOSE 3000

COPY . ./app
WORKDIR /app/frontend

ARG REACT_APP_SERVER_ARG
ENV REACT_APP_SERVER=${REACT_APP_SERVER_ARG}
ENV REACT_APP_MODE="frontend"

RUN corepack enable
RUN yarn install --frozen-lockfile
RUN yarn build
RUN yarn global add serve

CMD ["serve", "-s", "-n", "build"]

